/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_geekscircle_jni_JNIBASIC */

#ifndef _Included_com_geekscircle_jni_JNIBASIC
#define _Included_com_geekscircle_jni_JNIBASIC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_geekscircle_jni_JNIBASIC
 * Method:    helloWorld
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_geekscircle_jni_JNIBASIC_helloWorld
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
